[redirector]
protocol = ["HTTP"]
  - list, so if one gets burned, can resort to a different profile
  - HTTP/HTTPS, SMTP, ICMP, TCP, DNS, VoIP?
type = "LONGHAUL"
  - LONGHAUL, SHORTHAUL, PHISH, PAYLOAD
profile = ["/path/to/profile"]
  - ordered list, so when one gets burned and another protocol is selected, profile will match



- would be pretty cool to generate compiled implants for each class of teamserver
- deploy chat servers that can be burned and monitor unwanted traffic
  - chat logs should be backed up but encrypted
- backups, *especially* making sure every command that is run is recorded for audit/compliance
