- become: yes
  hosts: http-redir 
  name: http-redir-ubuntu setup
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: latest
        update_cache: yes

    - name: Enable rewrite module
      apache2_module:
        name: rewrite
        state: present
        ignore_configcheck: True

    - name: Enable proxy module
      apache2_module:
        name: proxy 
        state: present
        ignore_configcheck: True

    - name: Enable proxy_http module
      apache2_module:
        name: proxy_http 
        state: present
        ignore_configcheck: True

    - name: Replace apache2.conf file
      copy:
        src: configs/apache2.conf
        dest: /etc/apache2/apache2.conf
        owner: root
        group: root
        mode: '0644'

    - name: Replace .htaccess file
      copy:
        src: configs/.htaccess
        dest: /var/www/html/.htaccess
        owner: root
        group: root
        mode: '0644'

    - name: Restart apache2
      service:
        name: apache2
        state: restarted
